/**
 * UI-chrome translations. GENERATED from the Citizenly website's
 * forourparents/lib/i18n.ts by scripts (gen-ui-strings.js in the session
 * scratchpad) - the site dictionary is complete in all 48 languages, so every
 * entry here is too. English values are the app's own copy and may differ
 * from the site's ("Not quite right" vs "Incorrect"); the other 47 languages
 * are the site's translations for the equivalent slot.
 *
 * Hand-edits are fine (this file is the source of truth for the app); add new
 * keys with at least { en } - t() falls back to English per string.
 */

import type { LanguageCode } from '@/constants/brand';

export type UiEntry = { en: string } & Partial<Record<LanguageCode, string>>;

export const UI_STRINGS = {
  // site key "landingGetStarted" (site en: "GET STARTED")
  getStarted: {
    en: "Get Started",
    es: "Comenzar",
    zh: "立即开始",
    tl: "Magsimula",
    vi: "Bắt đầu",
    pl: "Zacznij teraz",
    fr: "Commencer",
    ko: "시작하기",
    ru: "Начать",
    hi: "शुरू करें",
    pt: "Começar",
    de: "Jetzt starten",
    it: "Inizia ora",
    gu: "શરૂ કરો",
    uk: "Почати",
    el: "Ξεκινήστε",
    hmn: "Pib",
    ml: "ആരംഭിക്കുക",
    ro: "Începeți",
    nl: "Aan de slag",
    sr: "Започните",
    bs: "Započnite",
    hr: "Započnite",
    bg: "Започнете",
    cs: "Začít",
    hu: "Kezdés",
    sk: "Začať",
    sl: "Začnite",
    ja: "始める",
    th: "เริ่มต้นใช้งาน",
    km: "ចាប់ផ្តើម",
    zht: "立即開始",
    tr: "Başlayın",
    lt: "Pradėti",
    lv: "Sākt",
    et: "Alustage",
    ptpt: "Começar",
    ca: "Començar",
    ta: "தொடங்குங்கள்",
    ht: "Kòmanse",
    ar: "ابدأ الآن",
    he: "בואו נתחיל",
    sq: "Filloni",
    id: "Mulai sekarang",
    sv: "Kom igång",
    no: "Kom i gang",
    da: "Kom i gang",
    fi: "Aloita",
  },
  // site key "landingAlreadyHave" (site en: "I ALREADY HAVE AN ACCOUNT")
  alreadyHaveAccount: {
    en: "I already have an account",
    es: "Ya tengo una cuenta",
    zh: "我已经有账户了",
    tl: "Mayroon na akong account",
    vi: "Tôi đã có tài khoản",
    pl: "Mam już konto",
    fr: "J'ai déjà un compte",
    ko: "이미 계정이 있습니다",
    ru: "У меня уже есть аккаунт",
    hi: "मेरे पास पहले से एक खाता है",
    pt: "Já tenho uma conta",
    de: "Ich habe bereits ein Konto",
    it: "Ho già un account",
    gu: "મારી પાસે પહેલેથી એકાઉન્ટ છે",
    uk: "У мене вже є обліковий запис",
    el: "Έχω ήδη λογαριασμό",
    hmn: "Kuv twb muaj account lawm",
    ml: "എനിക്ക് ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ട്",
    ro: "Am deja un cont",
    nl: "Ik heb al een account",
    sr: "Већ имам налог",
    bs: "Već imam nalog",
    hr: "Već imam račun",
    bg: "Вече имам акаунт",
    cs: "Již mám účet",
    hu: "Már van fiókom",
    sk: "Už mám účet",
    sl: "Že imam račun",
    ja: "すでにアカウントを持っています",
    th: "ฉันมีบัญชีอยู่แล้ว",
    km: "ខ្ញុំមានគណនីរួចហើយ",
    zht: "我已經有帳號了",
    tr: "Zaten bir hesabım var",
    lt: "Aš jau turiu paskyrą",
    lv: "Man jau ir konts",
    et: "Mul on juba konto",
    ptpt: "Já tenho uma conta",
    ca: "Ja tinc un compte",
    ta: "என்னிடம் ஏற்கனவே ஒரு கணக்கு உள்ளது",
    ht: "Mwen deja gen yon kont",
    ar: "لديّ حساب بالفعل",
    he: "כבר יש לי חשבון",
    sq: "Tashmë kam një llogari",
    id: "Saya sudah punya akun",
    sv: "Jag har redan ett konto",
    no: "Jeg har allerede en konto",
    da: "Jeg har allerede en konto",
    fi: "Minulla on jo tili",
  },
  // site key "login" (site en: "Login")
  logIn: {
    en: "Log In",
    es: "Iniciar sesión",
    zh: "登录",
    tl: "Mag-login",
    vi: "Đăng nhập",
    pl: "Zaloguj się",
    fr: "Connexion",
    ko: "로그인",
    ru: "Войти",
    hi: "लॉग इन",
    pt: "Entrar",
    de: "Anmelden",
    it: "Accedi",
    gu: "લોગિન",
    uk: "Вхід",
    el: "Σύνδεση",
    hmn: "Nkag Mus",
    ml: "ലോഗിൻ",
    ro: "Conectare",
    nl: "Inloggen",
    sr: "Пријава",
    bs: "Prijava",
    hr: "Prijava",
    bg: "Вход",
    cs: "Přihlášení",
    hu: "Bejelentkezés",
    sk: "Prihlásenie",
    sl: "Prijava",
    ja: "ログイン",
    th: "เข้าสู่ระบบ",
    km: "ចូលគណនី",
    zht: "登入",
    tr: "Giriş",
    lt: "Prisijungti",
    lv: "Pieteikties",
    et: "Sisselogimine",
    ptpt: "Iniciar sessão",
    ca: "Iniciar sessió",
    ta: "உள்நுழைவு",
    ht: "Konekte",
    ar: "تسجيل الدخول",
    he: "התחברות",
    sq: "Hyrje",
    id: "Masuk",
    sv: "Logga in",
    no: "Logg inn",
    da: "Log ind",
    fi: "Kirjaudu sisään",
  },
  // site key "logout" (site en: "Logout")
  logOut: {
    en: "Log Out",
    es: "Cerrar sesión",
    zh: "退出登录",
    tl: "Mag-logout",
    vi: "Đăng xuất",
    pl: "Wyloguj się",
    fr: "Déconnexion",
    ko: "로그아웃",
    ru: "Выйти",
    hi: "लॉग आउट",
    pt: "Sair",
    de: "Abmelden",
    it: "Esci",
    gu: "લોગઆઉટ",
    uk: "Вийти",
    el: "Αποσύνδεση",
    hmn: "Tawm Mus",
    ml: "ലോഗ് ഔട്ട്",
    ro: "Deconectare",
    nl: "Uitloggen",
    sr: "Одјава",
    bs: "Odjava",
    hr: "Odjava",
    bg: "Изход",
    cs: "Odhlásit se",
    hu: "Kijelentkezés",
    sk: "Odhlásiť sa",
    sl: "Odjava",
    ja: "ログアウト",
    th: "ออกจากระบบ",
    km: "ចាកចេញ",
    zht: "登出",
    tr: "Çıkış",
    lt: "Atsijungti",
    lv: "Iziet",
    et: "Logige välja",
    ptpt: "Terminar sessão",
    ca: "Tancar sessió",
    ta: "வெளியேறு",
    ht: "Dekonekte",
    ar: "تسجيل الخروج",
    he: "התנתקות",
    sq: "Dilni",
    id: "Keluar",
    sv: "Logga ut",
    no: "Logg ut",
    da: "Log ud",
    fi: "Kirjaudu ulos",
  },
  // site key "email"
  emailAddress: {
    en: "Email Address",
    es: "Correo electrónico",
    zh: "电子邮箱",
    tl: "Email Address",
    vi: "Địa chỉ email",
    pl: "Adres e-mail",
    fr: "Adresse e-mail",
    ko: "이메일 주소",
    ru: "Электронная почта",
    hi: "ईमेल पता",
    pt: "Endereço de e-mail",
    de: "E-Mail-Adresse",
    it: "Indirizzo e-mail",
    gu: "ઇમેઇલ સરનામું",
    uk: "Адреса електронної пошти",
    el: "Διεύθυνση email",
    hmn: "Email Chaw Nyob",
    ml: "ഇമെയിൽ വിലാസം",
    ro: "Adresă de e-mail",
    nl: "E-mailadres",
    sr: "Имејл адреса",
    bs: "E-mail adresa",
    hr: "E-mail adresa",
    bg: "Имейл адрес",
    cs: "E-mailová adresa",
    hu: "E-mail-cím",
    sk: "E-mailová adresa",
    sl: "E-naslov",
    ja: "メールアドレス",
    th: "ที่อยู่อีเมล",
    km: "អាសយដ្ឋានអ៊ីមែល",
    zht: "電子郵件地址",
    tr: "E-posta Adresi",
    lt: "El. pašto adresas",
    lv: "E-pasta adrese",
    et: "E-posti aadress",
    ptpt: "Endereço de correio eletrónico",
    ca: "Adreça electrònica",
    ta: "மின்னஞ்சல் முகவரி",
    ht: "Adrès Imèl",
    ar: "عنوان البريد الإلكتروني",
    he: "כתובת אימייל",
    sq: "Adresa e emailit",
    id: "Alamat Email",
    sv: "E-postadress",
    no: "E-postadresse",
    da: "E-mailadresse",
    fi: "Sähköpostiosoite",
  },
  // site key "cancel"
  cancel: {
    en: "Cancel",
    es: "Cancelar",
    zh: "取消",
    tl: "Kanselahin",
    vi: "Hủy",
    pl: "Anuluj",
    fr: "Annuler",
    ko: "취소",
    ru: "Отмена",
    hi: "रद्द करें",
    pt: "Cancelar",
    de: "Abbrechen",
    it: "Annulla",
    gu: "રદ કરો",
    uk: "Скасувати",
    el: "Ακύρωση",
    hmn: "Tso Tseg",
    ml: "റദ്ദാക്കുക",
    ro: "Anulați",
    nl: "Annuleren",
    sr: "Откажи",
    bs: "Otkaži",
    hr: "Odustani",
    bg: "Отказ",
    cs: "Zrušit",
    hu: "Mégse",
    sk: "Zrušiť",
    sl: "Prekliči",
    ja: "キャンセル",
    th: "ยกเลิก",
    km: "បោះបង់",
    zht: "取消",
    tr: "İptal",
    lt: "Atšaukti",
    lv: "Atcelt",
    et: "Tühistage",
    ptpt: "Cancelar",
    ca: "Cancel·lar",
    ta: "ரத்துசெய்",
    ht: "Anile",
    ar: "إلغاء",
    he: "ביטול",
    sq: "Anulo",
    id: "Batal",
    sv: "Avbryt",
    no: "Avbryt",
    da: "Annullér",
    fi: "Peruuta",
  },
  // site key "home"
  home: {
    en: "Home",
    es: "Inicio",
    zh: "首页",
    tl: "Tahanan",
    vi: "Trang chủ",
    pl: "Strona główna",
    fr: "Accueil",
    ko: "홈",
    ru: "Главная",
    hi: "होम",
    pt: "Início",
    de: "Startseite",
    it: "Home",
    gu: "હોમ",
    uk: "Головна",
    el: "Αρχική",
    hmn: "Tsev",
    ml: "ഹോം",
    ro: "Acasă",
    nl: "Home",
    sr: "Почетна",
    bs: "Početna",
    hr: "Početna",
    bg: "Начало",
    cs: "Domů",
    hu: "Kezdőlap",
    sk: "Domov",
    sl: "Domov",
    ja: "ホーム",
    th: "หน้าแรก",
    km: "ទំព័រដើម",
    zht: "首頁",
    tr: "Ana Sayfa",
    lt: "Pradžia",
    lv: "Sākums",
    et: "Avaleht",
    ptpt: "Início",
    ca: "Inici",
    ta: "முகப்பு",
    ht: "Akèy",
    ar: "الرئيسية",
    he: "בית",
    sq: "Kreu",
    id: "Beranda",
    sv: "Hem",
    no: "Hjem",
    da: "Hjem",
    fi: "Etusivu",
  },
  // site key "goHome" (site en: "Go Home")
  backToHome: {
    en: "Back to Home",
    es: "Ir al inicio",
    zh: "返回首页",
    tl: "Pumunta sa Tahanan",
    vi: "Về trang chủ",
    pl: "Wróć na stronę główną",
    fr: "Retour à l'accueil",
    ko: "홈으로",
    ru: "На главную",
    hi: "होम पर जाएँ",
    pt: "Ir para o início",
    de: "Zur Startseite",
    it: "Vai alla home",
    gu: "હોમ પર જાઓ",
    uk: "На головну",
    el: "Επιστροφή στην αρχική",
    hmn: "Mus Tsev",
    ml: "ഹോം പേജിലേക്ക്",
    ro: "Mergeți acasă",
    nl: "Naar home",
    sr: "Иди на почетну",
    bs: "Idi na početnu",
    hr: "Idi na početnu",
    bg: "Към началото",
    cs: "Na úvod",
    hu: "Kezdőlap",
    sk: "Na úvod",
    sl: "Na začetno stran",
    ja: "ホームへ",
    th: "กลับหน้าแรก",
    km: "ទៅទំព័រដើម",
    zht: "回到首頁",
    tr: "Ana Sayfaya Dön",
    lt: "Į pradžią",
    lv: "Uz sākumu",
    et: "Avalehele",
    ptpt: "Ir para o início",
    ca: "Anar a l'inici",
    ta: "முகப்புக்குச் செல்",
    ht: "Ale nan Akèy",
    ar: "العودة إلى الرئيسية",
    he: "לדף הבית",
    sq: "Shko te kreu",
    id: "Ke Beranda",
    sv: "Gå till startsidan",
    no: "Gå hjem",
    da: "Gå til forsiden",
    fi: "Etusivulle",
  },
  // site key "selectTopic"
  selectTopic: {
    en: "Select a Topic",
    es: "Elige un tema",
    zh: "选择一个主题",
    tl: "Pumili ng Paksa",
    vi: "Chọn một chủ đề",
    pl: "Wybierz temat",
    fr: "Choisissez un thème",
    ko: "주제 선택",
    ru: "Выберите тему",
    hi: "एक विषय चुनें",
    pt: "Escolha um tema",
    de: "Wählen Sie ein Thema",
    it: "Scegli un argomento",
    gu: "એક વિષય પસંદ કરો",
    uk: "Оберіть тему",
    el: "Επιλέξτε θέμα",
    hmn: "Xaiv Ib Lub Ntsiab Lus",
    ml: "ഒരു വിഷയം തിരഞ്ഞെടുക്കുക",
    ro: "Alegeți un subiect",
    nl: "Kies een onderwerp",
    sr: "Изаберите тему",
    bs: "Odaberite temu",
    hr: "Odaberite temu",
    bg: "Изберете тема",
    cs: "Vyberte téma",
    hu: "Válasszon témát",
    sk: "Vyberte tému",
    sl: "Izberite temo",
    ja: "トピックを選択",
    th: "เลือกหัวข้อ",
    km: "ជ្រើសរើសប្រធានបទ",
    zht: "選擇一個主題",
    tr: "Bir Konu Seçin",
    lt: "Pasirinkite temą",
    lv: "Izvēlieties tēmu",
    et: "Valige teema",
    ptpt: "Selecione um tema",
    ca: "Seleccioni un tema",
    ta: "ஒரு தலைப்பைத் தேர்ந்தெடுக்கவும்",
    ht: "Chwazi yon Sijè",
    ar: "اختر موضوعًا",
    he: "בחרו נושא",
    sq: "Zgjidhni një temë",
    id: "Pilih Topik",
    sv: "Välj ett ämne",
    no: "Velg et emne",
    da: "Vælg et emne",
    fi: "Valitse aihe",
  },
  // site key "practice" (site en: "Practice")
  modeStudy: {
    en: "Study Questions",
    es: "Practicar",
    zh: "练习",
    tl: "Magsanay",
    vi: "Luyện tập",
    pl: "Ćwicz",
    fr: "S'entraîner",
    ko: "연습",
    ru: "Практика",
    hi: "अभ्यास",
    pt: "Praticar",
    de: "Üben",
    it: "Esercitati",
    gu: "પ્રેક્ટિસ",
    uk: "Практика",
    el: "Εξάσκηση",
    hmn: "Xyaum",
    ml: "പരിശീലനം",
    ro: "Exersare",
    nl: "Oefenen",
    sr: "Вежбај",
    bs: "Vježbaj",
    hr: "Vježbaj",
    bg: "Упражнение",
    cs: "Procvičování",
    hu: "Gyakorlás",
    sk: "Precvičovanie",
    sl: "Vadba",
    ja: "練習",
    th: "ฝึกฝน",
    km: "អនុវត្ត",
    zht: "練習",
    tr: "Alıştırma",
    lt: "Praktika",
    lv: "Vingrināties",
    et: "Harjutage",
    ptpt: "Praticar",
    ca: "Pràctica",
    ta: "பயிற்சி",
    ht: "Pratike",
    ar: "تدرّب",
    he: "תרגול",
    sq: "Praktikë",
    id: "Latihan",
    sv: "Öva",
    no: "Øv",
    da: "Øv",
    fi: "Harjoittele",
  },
  // site key "flashcardMode" (site en: "Flashcard Mode")
  modeFlashcards: {
    en: "Flashcards",
    es: "Modo de tarjetas",
    zh: "抽认卡模式",
    tl: "Flashcard Mode",
    vi: "Chế độ thẻ ghi nhớ",
    pl: "Tryb fiszek",
    fr: "Mode de cartes",
    ko: "플래시카드 모드",
    ru: "Режим карточек",
    hi: "फ्लैशकार्ड मोड",
    pt: "Modo de cartões",
    de: "Karteikarten-Modus",
    it: "Modalità flashcard",
    gu: "ફ્લેશકાર્ડ મોડ",
    uk: "Режим карток",
    el: "Λειτουργία καρτών",
    hmn: "Hom Flashcard",
    ml: "ഫ്ലാഷ്കാർഡ് മോഡ്",
    ro: "Mod fișe",
    nl: "Flashcardmodus",
    sr: "Режим картица",
    bs: "Režim kartica",
    hr: "Način rada s karticama",
    bg: "Режим с карти",
    cs: "Režim kartiček",
    hu: "Kártya mód",
    sk: "Režim kartičiek",
    sl: "Način s karticami",
    ja: "フラッシュカードモード",
    th: "โหมดบัตรคำ",
    km: "របៀបកាតរំលឹក",
    zht: "字卡模式",
    tr: "Bilgi Kartı Modu",
    lt: "Kortelių režimas",
    lv: "Kartīšu režīms",
    et: "Kaardirežiim",
    ptpt: "Modo cartões",
    ca: "Mode targetes",
    ta: "நினைவட்டை முறை",
    ht: "Mòd Kat Flach",
    ar: "وضع البطاقات التعليمية",
    he: "מצב כרטיסיות",
    sq: "Modaliteti i kartelave",
    id: "Mode Kartu Belajar",
    sv: "Flashcard-läge",
    no: "Flashkort-modus",
    da: "Flashcard-tilstand",
    fi: "Muistikorttitila",
  },
  // site key "quizMode" (site en: "Quiz Mode")
  modeQuiz: {
    en: "Quiz",
    es: "Modo examen",
    zh: "测验模式",
    tl: "Mode ng Pagsusulit",
    vi: "Chế độ kiểm tra",
    pl: "Tryb quizu",
    fr: "Mode quiz",
    ko: "퀴즈 모드",
    ru: "Режим викторины",
    hi: "क्विज़ मोड",
    pt: "Modo quiz",
    de: "Quiz-Modus",
    it: "Modalità quiz",
    gu: "ક્વિઝ મોડ",
    uk: "Режим тесту",
    el: "Λειτουργία κουίζ",
    hmn: "Hom Xeem",
    ml: "ക്വിസ് മോഡ്",
    ro: "Mod test",
    nl: "Toetsmodus",
    sr: "Режим теста",
    bs: "Režim testa",
    hr: "Način testa",
    bg: "Режим на тест",
    cs: "Režim kvízu",
    hu: "Kvíz mód",
    sk: "Režim testu",
    sl: "Način kviza",
    ja: "クイズモード",
    th: "โหมดควิซ",
    km: "របៀបប្រឡង",
    zht: "測驗模式",
    tr: "Test Modu",
    lt: "Testo režimas",
    lv: "Testa režīms",
    et: "Testirežiim",
    ptpt: "Modo questionário",
    ca: "Mode qüestionari",
    ta: "வினாடி வினா முறை",
    ht: "Mòd Kwiz",
    ar: "وضع الاختبار",
    he: "מצב שאלון",
    sq: "Modaliteti i kuizit",
    id: "Mode Kuis",
    sv: "Provläge",
    no: "Quiz-modus",
    da: "Prøvetilstand",
    fi: "Koetila",
  },
  // site key "reviewMistakes"
  modeReviewMistakes: {
    en: "Review Mistakes",
    es: "Revisar errores",
    zh: "复习错题",
    tl: "Suriin ang mga Pagkakamali",
    vi: "Xem lại lỗi sai",
    pl: "Powtórz błędy",
    fr: "Revoir les erreurs",
    ko: "오답 복습",
    ru: "Разбор ошибок",
    hi: "गलतियाँ देखें",
    pt: "Revisar erros",
    de: "Fehler wiederholen",
    it: "Rivedi gli errori",
    gu: "ભૂલો તપાસો",
    uk: "Повторити помилки",
    el: "Επανάληψη λαθών",
    hmn: "Xyuas Kev Yuam Kev",
    ml: "തെറ്റുകൾ പരിശോധിക്കുക",
    ro: "Recapitulați greșelile",
    nl: "Fouten herhalen",
    sr: "Понови грешке",
    bs: "Ponovi greške",
    hr: "Ponovi pogreške",
    bg: "Преглед на грешките",
    cs: "Projít chyby",
    hu: "Hibák átnézése",
    sk: "Prejsť chyby",
    sl: "Preglejte napake",
    ja: "間違えた問題を復習",
    th: "ทบทวนข้อที่ผิด",
    km: "ពិនិត្យកំហុសឡើងវិញ",
    zht: "複習錯題",
    tr: "Hataları Gözden Geçir",
    lt: "Peržiūrėti klaidas",
    lv: "Pārskatīt kļūdas",
    et: "Vaadake vead üle",
    ptpt: "Rever erros",
    ca: "Revisar els errors",
    ta: "தவறுகளை மீள்பார்வை",
    ht: "Revize Erè yo",
    ar: "مراجعة الأخطاء",
    he: "סקירת טעויות",
    sq: "Rishikoni gabimet",
    id: "Tinjau Kesalahan",
    sv: "Repetera fel",
    no: "Gjennomgå feil",
    da: "Repetér fejl",
    fi: "Kertaa virheet",
  },
  // site key "correct"
  correctBanner: {
    en: "Correct!",
    es: "¡Correcto!",
    zh: "正确！",
    tl: "Tama!",
    vi: "Đúng!",
    pl: "Poprawnie!",
    fr: "Correct !",
    ko: "정답!",
    ru: "Правильно!",
    hi: "सही!",
    pt: "Correto!",
    de: "Richtig!",
    it: "Corretto!",
    gu: "સાચું!",
    uk: "Правильно!",
    el: "Σωστά!",
    hmn: "Raug!",
    ml: "ശരി!",
    ro: "Corect!",
    nl: "Juist!",
    sr: "Тачно!",
    bs: "Tačno!",
    hr: "Točno!",
    bg: "Вярно!",
    cs: "Správně!",
    hu: "Helyes!",
    sk: "Správne!",
    sl: "Pravilno!",
    ja: "正解！",
    th: "ถูกต้อง!",
    km: "ត្រឹមត្រូវ!",
    zht: "答對了！",
    tr: "Doğru!",
    lt: "Teisingai!",
    lv: "Pareizi!",
    et: "Õige!",
    ptpt: "Certo!",
    ca: "Correcte!",
    ta: "சரியானது!",
    ht: "Kòrèk!",
    ar: "إجابة صحيحة!",
    he: "נכון!",
    sq: "Saktë!",
    id: "Benar!",
    sv: "Rätt!",
    no: "Riktig!",
    da: "Rigtigt!",
    fi: "Oikein!",
  },
  // site key "incorrect" (site en: "Incorrect")
  wrongBanner: {
    en: "Not quite right",
    es: "Incorrecto",
    zh: "错误",
    tl: "Mali",
    vi: "Sai",
    pl: "Niepoprawnie",
    fr: "Incorrect",
    ko: "오답",
    ru: "Неправильно",
    hi: "गलत",
    pt: "Incorreto",
    de: "Falsch",
    it: "Sbagliato",
    gu: "ખોટું",
    uk: "Неправильно",
    el: "Λάθος",
    hmn: "Tsis Raug",
    ml: "തെറ്റ്",
    ro: "Greșit",
    nl: "Onjuist",
    sr: "Нетачно",
    bs: "Netačno",
    hr: "Netočno",
    bg: "Грешно",
    cs: "Špatně",
    hu: "Helytelen",
    sk: "Nesprávne",
    sl: "Napačno",
    ja: "不正解",
    th: "ไม่ถูกต้อง",
    km: "មិនត្រឹមត្រូវ",
    zht: "答錯了",
    tr: "Yanlış",
    lt: "Neteisingai",
    lv: "Nepareizi",
    et: "Vale",
    ptpt: "Errado",
    ca: "Incorrecte",
    ta: "தவறானது",
    ht: "Pa kòrèk",
    ar: "إجابة خاطئة",
    he: "לא נכון",
    sq: "Gabim",
    id: "Salah",
    sv: "Fel",
    no: "Feil",
    da: "Forkert",
    fi: "Väärin",
  },
  // site key "quizComplete"
  quizComplete: {
    en: "Quiz Complete!",
    es: "¡Examen completado!",
    zh: "测验完成！",
    tl: "Tapos na ang Pagsusulit!",
    vi: "Hoàn thành bài kiểm tra!",
    pl: "Quiz ukończony!",
    fr: "Quiz terminé !",
    ko: "퀴즈 완료!",
    ru: "Викторина завершена",
    hi: "क्विज़ पूरी हुई!",
    pt: "Quiz concluído!",
    de: "Quiz abgeschlossen!",
    it: "Quiz completato!",
    gu: "ક્વિઝ પૂરી થઈ!",
    uk: "Тест завершено!",
    el: "Το κουίζ ολοκληρώθηκε!",
    hmn: "Kev Xeem Tiav!",
    ml: "ക്വിസ് പൂർത്തിയായി!",
    ro: "Test finalizat!",
    nl: "Toets afgerond!",
    sr: "Тест је завршен!",
    bs: "Test je završen!",
    hr: "Test je završen!",
    bg: "Тестът е завършен!",
    cs: "Kvíz dokončen!",
    hu: "Kvíz befejezve!",
    sk: "Test dokončený!",
    sl: "Kviz končan!",
    ja: "クイズ完了！",
    th: "ทำควิซเสร็จสิ้น!",
    km: "ការប្រឡងបានបញ្ចប់!",
    zht: "測驗完成！",
    tr: "Test Tamamlandı!",
    lt: "Testas baigtas!",
    lv: "Tests pabeigts!",
    et: "Test läbitud!",
    ptpt: "Questionário concluído!",
    ca: "Qüestionari completat!",
    ta: "வினாடி வினா முடிந்தது!",
    ht: "Kwiz la Fini!",
    ar: "اكتمل الاختبار!",
    he: "המבחן הושלם!",
    sq: "Kuizi përfundoi!",
    id: "Kuis Selesai!",
    sv: "Provet är klart!",
    no: "Quiz fullført!",
    da: "Prøven er gennemført!",
    fi: "Koe suoritettu!",
  },
  // site key "tryAgain"
  tryAgain: {
    en: "Try Again",
    es: "Intentar de nuevo",
    zh: "再试一次",
    tl: "Subukan Muli",
    vi: "Thử lại",
    pl: "Spróbuj ponownie",
    fr: "Réessayer",
    ko: "다시 시도",
    ru: "Попробовать снова",
    hi: "फिर से प्रयास करें",
    pt: "Tentar novamente",
    de: "Erneut versuchen",
    it: "Riprova",
    gu: "ફરી પ્રયત્ન કરો",
    uk: "Спробувати ще раз",
    el: "Δοκιμάστε ξανά",
    hmn: "Sim Dua",
    ml: "വീണ്ടും ശ്രമിക്കുക",
    ro: "Încercați din nou",
    nl: "Probeer opnieuw",
    sr: "Покушај поново",
    bs: "Pokušaj ponovo",
    hr: "Pokušaj ponovno",
    bg: "Опитай отново",
    cs: "Zkusit znovu",
    hu: "Próbálja újra",
    sk: "Skúsiť znova",
    sl: "Poskusite znova",
    ja: "もう一度",
    th: "ลองอีกครั้ง",
    km: "ព្យាយាមម្តងទៀត",
    zht: "再試一次",
    tr: "Tekrar Deneyin",
    lt: "Bandyti dar kartą",
    lv: "Mēģināt vēlreiz",
    et: "Proovige uuesti",
    ptpt: "Tentar novamente",
    ca: "Tornar-ho a provar",
    ta: "மீண்டும் முயற்சிக்கவும்",
    ht: "Eseye Ankò",
    ar: "حاول مرة أخرى",
    he: "נסו שוב",
    sq: "Provo përsëri",
    id: "Coba Lagi",
    sv: "Försök igen",
    no: "Prøv igjen",
    da: "Prøv igen",
    fi: "Yritä uudelleen",
  },
  // site key "next"
  next: {
    en: "Next",
    es: "Siguiente",
    zh: "下一个",
    tl: "Susunod",
    vi: "Tiếp",
    pl: "Dalej",
    fr: "Suivant",
    ko: "다음",
    ru: "Далее",
    hi: "आगे",
    pt: "Próximo",
    de: "Weiter",
    it: "Avanti",
    gu: "આગળ",
    uk: "Далі",
    el: "Επόμενο",
    hmn: "Tom Ntej",
    ml: "അടുത്തത്",
    ro: "Următorul",
    nl: "Volgende",
    sr: "Следеће",
    bs: "Sljedeće",
    hr: "Sljedeće",
    bg: "Напред",
    cs: "Další",
    hu: "Tovább",
    sk: "Ďalej",
    sl: "Naprej",
    ja: "次へ",
    th: "ถัดไป",
    km: "បន្ទាប់",
    zht: "下一個",
    tr: "İleri",
    lt: "Toliau",
    lv: "Tālāk",
    et: "Edasi",
    ptpt: "Seguinte",
    ca: "Següent",
    ta: "அடுத்து",
    ht: "Swivan",
    ar: "التالي",
    he: "הבא",
    sq: "Tjetra",
    id: "Lanjut",
    sv: "Nästa",
    no: "Neste",
    da: "Næste",
    fi: "Seuraava",
  },
  // site key "iGotIt" (site en: "I got it ✓")
  gotIt: {
    en: "Got it",
    es: "Lo sé ✓",
    zh: "我答对了 ✓",
    tl: "Tama ako ✓",
    vi: "Tôi đúng ✓",
    pl: "Wiedziałem/am ✓",
    fr: "J'ai réussi ✓",
    ko: "맞췄어요 ✓",
    ru: "Я знаю ✓",
    hi: "मुझे आता है ✓",
    pt: "Acertei ✓",
    de: "Gewusst ✓",
    it: "Lo sapevo ✓",
    gu: "મને આવડ્યું ✓",
    uk: "Я знав ✓",
    el: "Το ήξερα ✓",
    hmn: "Kuv paub lawm ✓",
    ml: "എനിക്ക് കിട്ടി ✓",
    ro: "Am știut ✓",
    nl: "Ik wist het ✓",
    sr: "Знао сам ✓",
    bs: "Znao sam ✓",
    hr: "Znao sam ✓",
    bg: "Познах ✓",
    cs: "Vím to ✓",
    hu: "Tudtam ✓",
    sk: "Viem to ✓",
    sl: "Vem ✓",
    ja: "わかった ✓",
    th: "ฉันตอบได้ ✓",
    km: "ខ្ញុំយល់ហើយ ✓",
    zht: "我答對了 ✓",
    tr: "Bildim ✓",
    lt: "Atsakiau teisingai ✓",
    lv: "Es zināju ✓",
    et: "Teadsin ✓",
    ptpt: "Acertei ✓",
    ca: "Ho he encertat ✓",
    ta: "எனக்குப் புரிந்தது ✓",
    ht: "Mwen jwenn li ✓",
    ar: "أجبت بشكل صحيح ✓",
    he: "עניתי נכון ✓",
    sq: "E kuptova ✓",
    id: "Saya benar ✓",
    sv: "Jag kunde det ✓",
    no: "Jeg klarte det ✓",
    da: "Jeg kunne det ✓",
    fi: "Osasin ✓",
  },
  // site key "readAloud" (site en: "Read Aloud")
  readAloud: {
    en: "Read aloud",
    es: "Leer en voz alta",
    zh: "朗读",
    tl: "Basahin nang Malakas",
    vi: "Đọc to",
    pl: "Przeczytaj na głos",
    fr: "Lire à voix haute",
    ko: "소리내어 읽기",
    ru: "Прочитать вслух",
    hi: "ज़ोर से पढ़ें",
    pt: "Ler em voz alta",
    de: "Vorlesen",
    it: "Leggi ad alta voce",
    gu: "મોટેથી વાંચો",
    uk: "Читати вголос",
    el: "Ανάγνωση φωναχτά",
    hmn: "Nyeem Nrov Nrov",
    ml: "ഉറക്കെ വായിക്കുക",
    ro: "Citiți cu voce tare",
    nl: "Voorlezen",
    sr: "Прочитај наглас",
    bs: "Pročitaj naglas",
    hr: "Pročitaj naglas",
    bg: "Прочети на глас",
    cs: "Číst nahlas",
    hu: "Felolvasás",
    sk: "Čítať nahlas",
    sl: "Preberi na glas",
    ja: "読み上げ",
    th: "อ่านออกเสียง",
    km: "អានឮៗ",
    zht: "朗讀",
    tr: "Sesli Oku",
    lt: "Skaityti balsu",
    lv: "Nolasīt skaļi",
    et: "Lugege ette",
    ptpt: "Ler em voz alta",
    ca: "Llegir en veu alta",
    ta: "உரக்கப் படியுங்கள்",
    ht: "Li awotvwa",
    ar: "اقرأ بصوت عالٍ",
    he: "הקראה",
    sq: "Lexoni me zë",
    id: "Bacakan",
    sv: "Läs upp",
    no: "Les høyt",
    da: "Læs højt",
    fi: "Lue ääneen",
  },
  // site key "missed"
  missed: {
    en: "Missed",
    es: "Falladas",
    zh: "答错",
    tl: "Mali",
    vi: "Sai",
    pl: "Błędne",
    fr: "Manquées",
    ko: "틀림",
    ru: "Ошибок",
    hi: "चूके",
    pt: "Erradas",
    de: "Verfehlt",
    it: "Sbagliate",
    gu: "ચૂક્યા",
    uk: "Помилок",
    el: "Λάθη",
    hmn: "Tsis Raug",
    ml: "തെറ്റിയത്",
    ro: "Greșite",
    nl: "Fout",
    sr: "Нетачно",
    bs: "Netačno",
    hr: "Netočno",
    bg: "Пропуснати",
    cs: "Chyb",
    hu: "Hibás",
    sk: "Chýb",
    sl: "Napačnih",
    ja: "不正解",
    th: "ตอบผิด",
    km: "ឆ្លើយខុស",
    zht: "答錯",
    tr: "Bilinemeyen",
    lt: "Praleista",
    lv: "Kļūdas",
    et: "Valed",
    ptpt: "Falhadas",
    ca: "Errades",
    ta: "தவறவிட்டவை",
    ht: "Rate",
    ar: "الأخطاء",
    he: "פוספסו",
    sq: "Të humbura",
    id: "Salah",
    sv: "Fel",
    no: "Bommet",
    da: "Forkerte",
    fi: "Väärin",
  },
  // site key "mistakesEncourage"
  mistakesEncourage: {
    en: "Don't worry! Mistakes help us learn.",
    es: "¡No te preocupes! Los errores nos ayudan a aprender.",
    zh: "别担心！错误帮助我们进步。",
    tl: "Huwag mag-alala! Ang mga pagkakamali ay nakakatulong sa pagkatuto.",
    vi: "Đừng lo! Sai lầm giúp chúng ta học hỏi.",
    pl: "Bez obaw! Błędy pomagają się uczyć.",
    fr: "Ne vous inquiétez pas ! Les erreurs nous aident à apprendre.",
    ko: "걱정하지 마세요! 오답은 학습에 도움이 됩니다.",
    ru: "Не переживайте. Ошибки помогают нам учиться.",
    hi: "चिंता न करें! गलतियाँ हमें सीखने में मदद करती हैं।",
    pt: "Não se preocupe! Os erros nos ajudam a aprender.",
    de: "Keine Sorge! Fehler helfen uns beim Lernen.",
    it: "Non preoccuparti! Gli errori ci aiutano a imparare.",
    gu: "ચિંતા ન કરો! ભૂલો શીખવામાં મદદ કરે છે.",
    uk: "Не хвилюйтеся! Помилки допомагають нам вчитися.",
    el: "Μην ανησυχείτε! Τα λάθη μάς βοηθούν να μαθαίνουμε.",
    hmn: "Txhob txhawj! Kev yuam kev pab peb kawm.",
    ml: "വിഷമിക്കേണ്ട! തെറ്റുകൾ പഠിക്കാൻ സഹായിക്കും.",
    ro: "Nu vă faceți griji! Greșelile ne ajută să învățăm.",
    nl: "Geen zorgen! Van fouten leren we.",
    sr: "Не брините! Грешке нам помажу да научимо.",
    bs: "Ne brinite! Greške nam pomažu da naučimo.",
    hr: "Ne brinite! Pogreške nam pomažu da naučimo.",
    bg: "Не се притеснявайте! Грешките ни помагат да учим.",
    cs: "Nebojte se! Chyby nám pomáhají se učit.",
    hu: "Ne aggódjon! A hibák segítenek a tanulásban.",
    sk: "Nebojte sa! Chyby nám pomáhajú učiť sa.",
    sl: "Ne skrbite! Napake nam pomagajo pri učenju.",
    ja: "ご心配なく！間違いは学びに役立ちます。",
    th: "ไม่ต้องกังวล! ข้อที่ผิดช่วยให้เราเรียนรู้",
    km: "កុំបារម្ភ! កំហុសជួយឱ្យយើងរៀនកាន់តែច្រើន។",
    zht: "別擔心！錯誤能幫助我們學習。",
    tr: "Endişelenmeyin! Hatalar öğrenmemize yardımcı olur.",
    lt: "Nesijaudinkite! Klaidos padeda mums mokytis.",
    lv: "Neuztraucieties! Kļūdas palīdz mums mācīties.",
    et: "Ärge muretsege! Vead aitavad meil õppida.",
    ptpt: "Não se preocupe! Os erros ajudam-nos a aprender.",
    ca: "No es preocupi! Els errors ens ajuden a aprendre.",
    ta: "கவலைப்படாதீர்கள்! தவறுகள் நமக்குக் கற்றுக்கொள்ள உதவுகின்றன.",
    ht: "Pa enkyete ou! Erè ede nou aprann.",
    ar: "لا تقلق! الأخطاء تساعدنا على التعلّم.",
    he: "אל דאגה! טעויות עוזרות לנו ללמוד.",
    sq: "Mos u shqetësoni! Gabimet na ndihmojnë të mësojmë.",
    id: "Jangan khawatir! Kesalahan membantu kita belajar.",
    sv: "Oroa dig inte! Fel hjälper oss att lära oss.",
    no: "Ikke vær redd! Feil hjelper oss å lære.",
    da: "Bare rolig! Fejl hjælper os med at lære.",
    fi: "Ei hätää! Virheistä oppii.",
  },
  // composed from site keys "questionOf" + "of", same word order the website uses
  questionXofY: {
    en: "Question {current} of {total}",
    es: "Pregunta {current} de {total}",
    zh: "第 {current} 题，共 {total}",
    tl: "Tanong {current} ng {total}",
    vi: "Câu hỏi {current} / {total}",
    pl: "Pytanie {current} z {total}",
    fr: "Question {current} sur {total}",
    ko: "문제 {current} / {total}",
    ru: "Вопрос {current} из {total}",
    hi: "प्रश्न {current} में से {total}",
    pt: "Pergunta {current} de {total}",
    de: "Frage {current} von {total}",
    it: "Domanda {current} di {total}",
    gu: "પ્રશ્ન {current} / {total}",
    uk: "Запитання {current} з {total}",
    el: "Ερώτηση {current} από {total}",
    hmn: "Lus Nug {current} ntawm {total}",
    ml: "ചോദ്യം {current} / {total}",
    ro: "Întrebarea {current} din {total}",
    nl: "Vraag {current} van {total}",
    sr: "Питање {current} од {total}",
    bs: "Pitanje {current} od {total}",
    hr: "Pitanje {current} od {total}",
    bg: "Въпрос {current} от {total}",
    cs: "Otázka {current} z {total}",
    hu: "Kérdés {current} / {total}",
    sk: "Otázka {current} z {total}",
    sl: "Vprašanje {current} od {total}",
    ja: "問題 {current} / {total}",
    th: "คำถาม {current} จาก {total}",
    km: "សំណួរ {current} នៃ {total}",
    zht: "第 {current} 題，共 {total}",
    tr: "Soru {current} / {total}",
    lt: "Klausimas {current} iš {total}",
    lv: "Jautājums {current} no {total}",
    et: "Küsimus {current} / {total}",
    ptpt: "Pergunta {current} de {total}",
    ca: "Pregunta {current} de {total}",
    ta: "கேள்வி {current} இல் {total}",
    ht: "Kesyon {current} sou {total}",
    ar: "السؤال {current} من {total}",
    he: "שאלה {current} מתוך {total}",
    sq: "Pyetja {current} nga {total}",
    id: "Pertanyaan {current} dari {total}",
    sv: "Fråga {current} av {total}",
    no: "Spørsmål {current} av {total}",
    da: "Spørgsmål {current} af {total}",
    fi: "Kysymys {current} / {total}",
  },

  // Read-aloud controls. English-only for now - t() falls back per string,
  // so these render in English until translations are added.
  stopReading: {
    en: "Stop reading",
  },
  autoSpeakTitle: {
    en: "Read answers aloud",
  },
  autoSpeakOn: {
    en: "Answers and explanations are spoken automatically.",
  },
  autoSpeakOff: {
    en: "Tap the speaker button when you want to hear something.",
  },
} as const satisfies Record<string, UiEntry>;

export type UiKey = keyof typeof UI_STRINGS;

/**
 * Plural-aware entries: per-language forms keyed by Intl.PluralRules
 * categories. Currently English-only - other languages fall back to English
 * until translated (same per-string fallback as UI_STRINGS).
 */
export type UiPluralForms = Partial<Record<Intl.LDMLPluralRule, string>> & { other: string };
export type UiPluralEntry = { en: UiPluralForms } & Partial<
  Record<LanguageCode, UiPluralForms>
>;

export const UI_PLURALS = {
  questionsCount: {
    en: { one: '{count} question', other: '{count} questions' },
  },
  quizSummary: {
    en: {
      one: 'You answered {score} of {total} question correctly.',
      other: 'You answered {score} of {total} questions correctly.',
    },
  },
} as const satisfies Record<string, UiPluralEntry>;

export type UiPluralKey = keyof typeof UI_PLURALS;
